name: "gms-app"
services:
  web-server:
    image: ghcr.io/nkarisa/gms:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "${APP_PORT:-8030}:8080"
    depends_on:
      - redis-session-cache
      - mysql-server
    networks:
      - ezesha

  redis-session-cache:
    image: redis:7.2.10-alpine
    restart: always
    volumes:
      - gms-redis-data:/data
    ports:
      - "6389:6379"
    networks:
      - ezesha
  
  mysql-server:
    image: mysql:8.0
    restart: always
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-gms_db}
      MYSQL_USER: ${MYSQL_USER:-gms_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-gms_pass}
    ports:
      - "3307:3306"
    volumes:
      - gms-mysql-data:/var/lib/mysql
    networks:
      - ezesha

  # mysql-server:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE:-gms_db}
  #     MYSQL_USER: ${MYSQL_USER:-gms_user}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD:-gms_pass}
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - gms-mysql-data:/var/lib/mysql
  #   networks:
  #     - ezesha
  
  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #   environment:
  #     # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
  #     - DEBUG=${DEBUG:-0}
  #     - LAMBDA_PREWARM_CONTAINERS=1
  #   volumes:
  #     - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "./entrypoint.d:/etc/localstack/init/ready.d"

volumes:
  gms-redis-data:
    name: gms-redis-data
    external: true
  gms-mysql-data:
    name: gms-mysql-data
    external: true

networks:
  ezesha:
    driver: bridge